spring.application.name=FitCore

# PostgreSQL - Neon
spring.datasource.url=jdbc:postgresql://ep-delicate-math-b4i9bo89-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_PzYLCAIyR02T

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=8080